# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b5d80f8ba5e9c869ffaf8018a47ccfb0c4193d3f883facfb3549a8238428ba100908b70a8362330031890f59f81501d0f74ca71fc1f2e688cf25ab922364eb7

test:
  secret_key_base: 5d48738ba6c4672060b3a233af803f6154e67c881a80b1fddc246841a341bc6ce4645dd93cda7664c3d4b8952b5c5b9542e34037a0d2ed9010519f9b6525d34f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
